#!/bin/bash

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
      . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# BEGIN LAMACHINE MANAGED BLOCK - path
if [[ "$PATH" != *"/home/mebasar/bin"* ]]; then
    export PATH=~/bin:$PATH #add ~/bin to $PATH, that is where the activation scripts are
fi
# END LAMACHINE MANAGED BLOCK - path
