#!/bin/bash

# Python
alias python='python3'

# Environments
alias src='. .env/bin/activate'
alias srch='. env/bin/activate'
alias lama='. ~/lamachine/bin/activate'

# Scripts to run
alias pmr='python manage.py runserver'
alias jnote='jupyter notebook'
# alias pyanac="export PATH='~/Anaconda3/bin:$PATH'"

# Git alias
alias gcam='git commit -am'
alias gcek='git checkout'

# Folder Navigation;
alias cdwork='cd ~/Dropbox/workspaces'
alias cdflo='cd ~/Dropbox/workspaces/Python/Floodtags_Dashboard'
alias cdeifd='cd ~/Dropbox/workspaces/Python/EIFD/'

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
