#!/bin/bash

# Python
# alias python='python3'

# Environments
alias src='. .env/bin/activate'
alias srch='. env/bin/activate'
alias lama='. ~/lamachine/bin/activate'
alias deac='deactivate'

# Program Shortcuts
alias pmr='python manage.py runserver'
alias jnote='jupyter notebook'
alias venv='virtualenv -p python3 .env'
# alias pyanac="export PATH='~/Anaconda3/bin:$PATH'"

# Git aliases
alias gadd='git add'
alias gaa='git add -A :/'
alias gcom='git commit'
alias gcam='git commit -am'
alias gcek='git checkout'
alias gsta='git status'
alias gbra='git branch'
alias gpus='git push'
alias gpul='git pull'
alias gclo='git clone'

# Folder Navigation;
alias ..="cd .."
alias cd..="cd .."
alias cdwork='cd ~/Dropbox/workspaces/'
alias cdflo='cd ~/Dropbox/workspaces/Web/Floodtags_Dashboard/'
alias cdeifd='cd ~/Dropbox/workspaces/Python/EIFD/'

# ls aliases
alias la='ls -A'
alias ll='ls -al'
alias lls='ls -lsh'

# Color support of ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Start Radboud Science VPN in a screen;
alias ruvpn='screen -S ruvpn bash -c "sudo openvpn $HOME/.dotfiles/vpn/openvpn-science-ru-nl.ovpn"'

# Add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
